apiVersion: v1
kind: Service

metadata:
  name: aspdotnetwebpp-service
  
  labels:
    app: aspdotnetwebpp

spec:
  ports:
    - name: aspdotnetwebpp-port
      port: 5000
      protocol: TCP
  
  selector:
    app: aspdotnetwebpp

  type: LoadBalancer
