apiVersion: v1
kind: Service

metadata:
  name: azsqledge-service

spec:
  selector:
    app: azsqledge
  
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      name: azsqledge
  
  type: LoadBalancer